export const codingTips = [
    { id: 1, category: "SÉCURITÉ", tip: "Protection DDoS Obligatoire", details: "$ sudo protection.enable() && cloudflare.deploy()" },
    { id: 2, category: "SANTÉ", tip: "console.log('Reste Hydraté')", details: "while(coding) { boire.eau(250ml); dormir(3600000); }" },
    { id: 3, category: "PERFORMANCE", tip: "Optimise Ton CPU Humain", details: "for(chaque_heure) { faire.pause(5min); etirer.corps(); }" },
    { id: 4, category: "OUTILS", tip: "Maîtrise Ton IDE", details: "vim.master() ? victoire++ : formation.continue();" },
    { id: 5, category: "MENTALITÉ", tip: "git commit -m \"Reste Concentré\"", details: "esprit.clear() && code.clean() && stress.reduce();" },
    { id: 6, category: "ÉQUIPE", tip: "Collaboration.sync()", details: "team.forEach(dev => dev.share(knowledge));" },
    { id: 7, category: "DEBUG", tip: "console.debug('Patience')", details: "bug === undefined ? feter() : garderCalme();" },
    { id: 8, category: "STRATÉGIE", tip: "Plan.execute()", details: "if(probleme.complexe) { diviser.pourRegner(); }" },
    { id: 9, category: "CAFÉ", tip: "try { coder() } catch { café++ }", details: "exception.handle(café.prepare({ force: 'maximale' }));" },
    { id: 10, category: "RÉSEAU", tip: "ping -c 3 collègues.local", details: "if(ping.failed) { allerAuBureau.now(); }" },
    { id: 11, category: "BUGS", tip: "git blame --no-offense", details: "const bug = new Promise((solve, cry) => { cry(); });" },
    { id: 12, category: "MOTIVATION", tip: "export const weekend = soon();", details: "setTimeout(weekend, 5 * 24 * 60 * 60 * 1000);" },
    { id: 13, category: "PRODUCTIVITÉ", tip: "rm -rf distractions/*", details: "focus.lock() && notifications.mute(true);" },
    { id: 14, category: "REPOS", tip: "async function weekend()", details: "await Promise.all([dormir(), netflix(), repos()]);" },
    { id: 15, category: "DEADLINE", tip: "git push --force-with-lease", details: "deadline.approaching ? panic() : procrastinate();" },
    { id: 16, category: "DOCUMENTATION", tip: "Doc.read()", details: "if (incertain) { consulter.documentation(); }" },
    { id: 17, category: "VERSIONING", tip: "git commit -m 'Sauvegarde fréquente'", details: "everyHour(() => { git.add('.'); git.commit('Sauvegarde automatique'); });" },
    { id: 18, category: "MOTIVATION", tip: "Ne jamais abandonner", details: "if (defi.difficile) { persévérer(); } else { continuer(); }" },
    { id: 19, category: "COLLABORATION", tip: "Code en équipe", details: "teamwork = codeQuality * 2;" },
    { id: 20, category: "TESTS", tip: "Tester c'est douter", details: "assert(codeFonctionne());" },
    { id: 21, category: "SÉCURITÉ", tip: "Toujours valider les entrées", details: "if (input == 'malicieux') { reject(); } else { accept(); }" },
    { id: 22, category: "EFFICIENCE", tip: "Automatise les tâches répétitives", details: "for (let tache of tachesRepetitives) { automatiser(tache); }" },
    { id: 23, category: "APPRENTISSAGE", tip: "Apprends quelque chose de nouveau", details: "if (tempsLibre > 0) { apprendre(nouvelleTechno); }" },
    { id: 24, category: "INSPIRATION", tip: "Regarde le code des autres", details: "openSourceProjects.forEach(projet => lire(projet.code));" },
    { id: 25, category: "DÉTENTE", tip: "Prends une pause café", details: "if (fatigue) { prendrePause(café); }" },
    { id: 26, category: "ERGONOMIE", tip: "Assure-toi d'être confortable", details: "if (dosDouleureux) { ajuster(chaise); }" },
    { id: 27, category: "PLANIFICATION", tip: "Planifie avant de coder", details: "if (projet.nouveau) { créer(plan); }" },
    { id: 28, category: "NETTOYAGE", tip: "Nettoie ton code", details: "code = code.replace(/codeMort/g, '');" },
    { id: 29, category: "COMMUNICATION", tip: "Parle à tes coéquipiers", details: "if (problème) { discuter(équipe); }" },
    { id: 30, category: "DÉBOGAGE", tip: "N'oublie pas le canard en plastique", details: "parler(duckDebugging);" },
    { id: 31, category: "SANTÉ", tip: "Garde une bonne posture", details: "if (assis.longtemps) { étirer(dos); }" },
    { id: 32, category: "INTERNET", tip: "Quand StackOverflow est en panne", details: "if (!stackoverflow) { panique(); }" },
    { id: 33, category: "RÉSEAU", tip: "Vérifie ta connexion", details: "if (codeNeMarchePas) { vérifier(internet); }" },
    { id: 34, category: "RÉSOLUTION DE PROBLÈME", tip: "Diviser pour régner", details: "problèmeComplexe.divideEn(sousProblèmes);" },
    { id: 35, category: "VERSIONING", tip: "Ne code pas en production", details: "if (enProduction) { nePasCoder(); }" },
    { id: 36, category: "URGENCE", tip: "Keep calm and code on", details: "if (deadline.proche) { garderCalme(); code(); }" },
    { id: 37, category: "TEMPS", tip: "Time.sleep(8 * 3600)", details: "if (nuit) { dormir(); }" },
    { id: 38, category: "FOCUS", tip: "Désactive les réseaux sociaux", details: "notifications.disable(['facebook', 'twitter']);" },
    { id: 39, category: "QUALITÉ", tip: "Code propre, esprit propre", details: "if (code.estPropre()) { esprit.purifié(); }" },
    { id: 40, category: "SÉCURITÉ", tip: "Ne partage pas tes mots de passe", details: "if (demandeMotDePasse) { refuser(); }" },
    { id: 41, category: "SANTÉ", tip: "N'oublie pas de manger", details: "if (ventre.gargouille) { manger(); }" },
    { id: 42, category: "PHILOSOPHIE", tip: "La réponse est 42", details: "if (question.ultime) { return 42; }" },
    { id: 43, category: "GESTION DE PROJET", tip: "Utilise des tickets", details: "if (bug.trouvé) { créer(ticket); }" },
    { id: 44, category: "DOCUMENTATION", tip: "Commente ton code", details: "if (code.confus) { ajouter(commentaires); }" },
    { id: 45, category: "BUGS", tip: "Les bugs se cachent dans les détails", details: "inspecter(code.lignes);" },
    { id: 46, category: "RÉSEAUX SOCIAUX", tip: "Évite les distractions", details: "while (travail) { éviter(reseauxSociaux); }" },
    { id: 47, category: "OPTIMISATION", tip: "N'optimise pas prématurément", details: "if (codeFonctionne) { nePasOptimiser(); }" },
    { id: 48, category: "APPRENTISSAGE", tip: "Partage tes connaissances", details: "if (collègue.demandeAide) { aider(); }" },
    { id: 49, category: "CONFIANCE", tip: "Fais confiance à ton code", details: "if (tests.passent) { déployer(); }" },
    { id: 50, category: "CAFÉ", tip: "Le café est ton ami", details: "if (somnolence) { boire(café); }" },
    { id: 51, category: "PAUSE", tip: "Prends le temps de respirer", details: "if (stressé) { respirer(); }" },
    { id: 52, category: "PRIORITÉS", tip: "Focus sur les tâches importantes", details: "tâches.sort(parImportance);" },
    { id: 53, category: "RECHERCHE", tip: "Google est ton ami", details: "if (bloqué) { rechercher('solution'); }" },
    { id: 54, category: "ÉQUIPE", tip: "Ne blâme pas les autres", details: "if (erreur) { chercher(solution); }" },
    { id: 55, category: "STYLING", tip: "Utilise un linter", details: "code = linter.apply(code);" },
    { id: 56, category: "TEMPS", tip: "Ne travaille pas trop tard", details: "if (heure > 22) { arrêter(); }" },
    { id: 57, category: "COMMUNICATION", tip: "Pose des questions", details: "if (doute) { demander(équipe); }" },
    { id: 58, category: "ORGANISATION", tip: "Garde ton bureau propre", details: "if (bureau.désordre) { ranger(); }" },
    { id: 59, category: "ENVIRONNEMENT", tip: "Configure ton environnement", details: "if (outilManquant) { installer(outil); }" },
    { id: 60, category: "FOCUS", tip: "Élimine les distractions", details: "activer(modeConcentration);" },
    { id: 61, category: "ADAPTABILITÉ", tip: "Sois prêt à changer de plan", details: "if (plan.échoue) { adapter(); }" },
    { id: 62, category: "SIMPLICITÉ", tip: "Garde les choses simples", details: "if (code.complexe) { simplifier(); }" },
    { id: 63, category: "CURIOSITÉ", tip: "Explore de nouvelles technologies", details: "if (tempsLibre) { expérimenter(); }" },
    { id: 64, category: "SANTÉ", tip: "N'oublie pas de cligner des yeux", details: "if (yeux.secs) { cligner(); }" },
    { id: 65, category: "GIT", tip: "git push origin master", details: "if (travail.terminé) { pousserVersDépôt(); }" },
    { id: 66, category: "SAUVEGARDE", tip: "Sauvegarde ton travail", details: "setInterval(sauvegarder, 3600000);" },
    { id: 67, category: "DEADLINE", tip: "Le temps passe vite", details: "if (deadline.approche) { accélérer(); }" },
    { id: 68, category: "MUSIQUE", tip: "Écoute de la musique", details: "if (silence) { play('playlist'); }" },
    { id: 69, category: "BONNES PRATIQUES", tip: "Respecte les standards", details: "if (code.nonConforme) { refactoriser(); }" },
    { id: 70, category: "PATIENCE", tip: "Rome ne s'est pas faite en un jour", details: "if (progrès.lents) { persévérer(); }" },
    { id: 71, category: "PERFORMANCE", tip: "Profile ton code", details: "if (performance.basse) { profiler(code); }" },
    { id: 72, category: "COMPATIBILITÉ", tip: "Teste sur plusieurs navigateurs", details: "navigateurs.forEach(tester);" },
    { id: 73, category: "SÉCURITÉ", tip: "Préviens les injections SQL", details: "requête = échapper(requête);" },
    { id: 74, category: "MOBILE", tip: "Responsive design", details: "if (écran.petit) { ajuster(interface); }" },
    { id: 75, category: "ACCESSIBILITÉ", tip: "Pense à tous les utilisateurs", details: "if (interface.nonAccessible) { améliorer(); }" },
    { id: 76, category: "TEAMBUILDING", tip: "Organise une activité d'équipe", details: "if (équipe.stressée) { planifier(teamBuilding); }" },
    { id: 77, category: "DÉVELOPPEMENT", tip: "N'oublie pas les tests unitaires", details: "if (code.ajouté) { écrire(testsUnitaires); }" },
    { id: 78, category: "SANTÉ MENTALE", tip: "Déconnecte-toi de temps en temps", details: "if (burnout) { prendre(vacances); }" },
    { id: 79, category: "APPRENTISSAGE", tip: "Participe à des meetups", details: "if (tempsLibre) { rejoindre(meetup); }" },
    { id: 80, category: "INNOVATION", tip: "Pense en dehors de la boîte", details: "if (solution.nonTrouvée) { innover(); }" },
    { id: 81, category: "RÉFLEXION", tip: "Prends du recul", details: "if (bloqué) { marcher(); réfléchir(); }" },
    { id: 82, category: "CODE", tip: "Écris du code que tu aimerais relire", details: "if (code.confus) { réécrire(); }" },
    { id: 83, category: "INSPIRATION", tip: "Regarde ce que font les leaders", details: "suivre(experts);" },
    { id: 84, category: "ESPRIT D'ÉQUIPE", tip: "Célébrez les victoires", details: "if (objectifAtteint) { fêter(); }" },
    { id: 85, category: "PRÉVOYANCE", tip: "Prévois les imprévus", details: "if (risque) { planifier(planB); }" },
    { id: 86, category: "BUGS", tip: "Les bugs arrivent, reste calme", details: "if (bug.apparaît) { respirer(); corriger(); }" },
    { id: 87, category: "DONNÉES", tip: "Sauvegarde tes données", details: "if (travail.crucial) { backup(); }" },
    { id: 88, category: "RÉUTILISATION", tip: "Ne réinvente pas la roue", details: "if (librairieExiste) { utiliser(librairie); }" },
    { id: 89, category: "TESTS", tip: "Teste tôt, teste souvent", details: "while (coding) { tester(); }" },
    { id: 90, category: "MENTORAT", tip: "Trouve un mentor", details: "if (envieProgresser) { chercher(mentor); }" },
    { id: 91, category: "CONNAISSANCE", tip: "Reste à jour", details: "if (technologie.évolue) { seMettreAJour(); }" },
    { id: 92, category: "OPTIMISATION", tip: "La simplicité est la clé", details: "if (code.compliqué) { simplifier(); }" },
    { id: 93, category: "CODE", tip: "Lis du code open-source", details: "projetsOpenSource.forEach(lireCode);" },
    { id: 94, category: "ÉNERGIE", tip: "Hydrate-toi régulièrement", details: "setInterval(boireEau, 3600000);" },
    { id: 95, category: "STRESS", tip: "Médite un instant", details: "if (tendu) { méditer(10); }" },
    { id: 96, category: "PRIORISATION", tip: "Fais une chose à la fois", details: "if (tâches.multiples) { prioriser(); }" },
    { id: 97, category: "HUMOUR", tip: "Les bugs sont des fonctionnalités cachées", details: "if (bug) { documenter(commeFonctionnalité); }" },
    { id: 98, category: "DÉCONNEXION", tip: "Passe du temps hors ligne", details: "if (enLigne.tropLongtemps) { déconnecter(); }" },
    { id: 99, category: "VISION", tip: "Garde l'œil sur l'objectif", details: "if (distrait) { recentrer(); }" },
    { id: 100, category: "SUCCÈS", tip: "Le succès est un voyage, pas une destination", details: "while (vivant) { apprendre(); grandir(); }" }
  ];
  
  export const categories = [
    "SÉCURITÉ",
    "SANTÉ",
    "PERFORMANCE",
    "OUTILS",
    "MENTALITÉ",
    "ÉQUIPE",
    "DEBUG",
    "STRATÉGIE",
    "CAFÉ",
    "RÉSEAU",
    "BUGS",
    "MOTIVATION",
    "PRODUCTIVITÉ",
    "REPOS",
    "DEADLINE",
    "DOCUMENTATION",
    "VERSIONING",
    "TESTS",
    "DÉTENTE",
    "ERGONOMIE",
    "PLANIFICATION",
    "NETTOYAGE",
    "COMMUNICATION",
    "RÉSOLUTION DE PROBLÈME",
    "URGENCE",
    "FOCUS",
    "QUALITÉ",
    "PHILOSOPHIE",
    "GESTION DE PROJET",
    "OPTIMISATION",
    "APPRENTISSAGE",
    "SANTÉ MENTALE",
    "INNOVATION",
    "PATIENCE",
    "COMPATIBILITÉ",
    "MOBILE",
    "ACCESSIBILITÉ",
    "TEAMBUILDING",
    "PRÉVOYANCE",
    "RÉUTILISATION",
    "MENTORAT",
    "CONNAISSANCE",
    "VISION",
    "SUCCÈS",
    "HUMOUR",
    "DÉCONNEXION"
  ];
  